server:
  port: 9999

spring:
  application:
    name: authorization-service
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: "@dmin@123"
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  boot:
    admin:
      client:
        url: http://localhost:8761/admin

jwt:
  secret: Zm9vYmFyYmF6cXV4eHl6Zm9vYmFyYmF6cXV4eHl6MTIzNDU2
  expiration: 3600000

logging:
  level:
    org:
      springframework:
        security: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    health-check:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 30  # Heartbeat interval
    lease-expiration-duration-in-seconds: 90


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      jvm: true
      process: true
      system: true