server:
  port: 9999

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: "@dmin@123"
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: Zm9vYmFyYmF6cXV4eHl6Zm9vYmFyYmF6cXV4eHl6MTIzNDU2
  expiration: 3600000

logging:
  level:
    org:
      springframework:
        security: DEBUG
