apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization-app
  template:
    metadata:
      labels:
        app: authorization-app
    spec:
      containers:
        - name: authorization-app
          image: authorization-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9999
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: authorization-configmap
            - secretRef:
                name: authorization-secrets
            
---
apiVersion: v1
kind: Service
metadata:
  name: authorization-service
  namespace: dev
spec:
  selector:
    app: authorization-app
  ports:
  - port: 9999
    targetPort: 9999