apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: dev
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=
  POSTGRES_DB: Z2VuZXJpY19vamt1
  POSTGRES_PASSWORD: cnFybFlDcDU1bWJMdXJjNzZ2MXc2OXdrUEFRdmZhZlU=
---
apiVersion: v1
kind: Secret
metadata:
  name: discovery-secrets
  namespace: dev
type: Opaque
data:
  SPRING_PROFILES_ACTIVE: ZGV2
  SPRING_CLOUD_CONFIG_SERVER_ENABLED: dHJ1ZQ==
  SPRING_CLOUD_CONFIG_SERVER_URI: aHR0cDovL3NlcnZpY2UtcmVnaXN0cnk6ODc2MS9jb25maWc=
---
apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
  namespace: dev
type: Opaque
data: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: authorization-secrets
  namespace: dev
type: Opaque
data:
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vZHBnLWQxZ2YyNTJsaTl2YzczYWl1OHZnLWEub3JlZ29uLXBvc3RncmVzLnJlbmRlci5jb20vZ2VuZXJpY19vamt1P3NzbD10cnVlJnNzbG1vZGU9cmVxdWlyZSZzc2xmYWN0b3J5PW9yZy5wb3N0Z3Jlc3FsLnNzbC5Ob25WYWxpZGF0aW5nRmFjdG9yeQ==
  SPRING_DATASOURCE_USERNAME: YWRtaW4=
  SPRING_DATASOURCE_PASSWORD: cnFybFlDcDU1bWJMdXJjNzZ2MXc2OXdrUEFRdmZhZlU=
  JWT_SECRET: Zm9vYmFyYmF6cXV4eHl6Zm9vYmFyYmF6cXV4eHl6MTIzNDU2
  JWT_EXPIRATION: MzYwMDAwMA==

---
apiVersion: v1
kind: Secret
metadata:
  name: user-secrets
  namespace: dev
type: Opaque
data:
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vZHBnLWQxZ2YyNTJsaTl2YzczYWl1OHZnLWEub3JlZ29uLXBvc3RncmVzLnJlbmRlci5jb20vZ2VuZXJpY19vamt1P3NzbD10cnVlJnNzbG1vZGU9cmVxdWlyZSZzc2xmYWN0b3J5PW9yZy5wb3N0Z3Jlc3FsLnNzbC5Ob25WYWxpZGF0aW5nRmFjdG9yeQ==
  SPRING_DATASOURCE_USERNAME: YWRtaW4=
  SPRING_DATASOURCE_PASSWORD: cnFybFlDcDU1bWJMdXJjNzZ2MXc2OXdrUEFRdmZhZlU=
  JWT_SECRET: Zm9vYmFyYmF6cXV4eHl6Zm9vYmFyYmF6cXV4eHl6MTIzNDU2
  JWT_EXPIRATION: MzYwMDAwMA==
