apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  namespace: dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: discovery-configmap
  namespace: dev
data:
  SERVER_PORT: "8761"
  SPRING_APPLICATION_NAME: discovery-server
  EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
  EUREKA_CLIENT_FETCH_REGISTRY: "false"
  EUREKA_SERVER_WAIT_TIME_IN_MS_WHEN_SYNC_EMPTY: "0"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-configmap
  namespace: dev
data:
  SPRING_APPLICATION_NAME: api-gateway
  SERVER_PORT: "8080"
  SPRING_MAIN_WEB_APPLICATION_TYPE: reactive

  EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
  EUREKA_CLIENT_FETCH_REGISTRY: "true"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry.dev.svc.cluster.local:8761/eureka

  SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED: "true"
  SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWER_CASE_SERVICE_ID: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authorization-configmap
  namespace: dev
data:
  SPRING_APPLICATION_NAME: authorization-service
  SERVER_PORT: "9999"
  SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED: "true"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG

  EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
  EUREKA_CLIENT_FETCH_REGISTRY: "true"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry.dev.svc.cluster.local:8761/eureka
  EUREKA_CLIENT_HEALTH_CHECK_ENABLED: "true"
  EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS: "30"
  EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS: "90"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-configmap
  namespace: dev
data:
  SPRING_APPLICATION_NAME: user-service
  SERVER_PORT: "8082"
  SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED: "true"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG

  EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
  EUREKA_CLIENT_FETCH_REGISTRY: "true"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry.dev.svc.cluster.local:8761/eureka
  EUREKA_CLIENT_HEALTH_CHECK_ENABLED: "true"
  EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS: "30"
  EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS: "90"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
