
server:
  port: 9092

resilience4j:
  circuitbreaker:
    instances:
      backendService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
